[book]
title = "魔王大人、RETRY！ (重來吧，魔王大人！) - LNGit 小說"
authors = ["神埼黑音"]
language = "zh-Hant"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
google-analytics = "UA-154804426-2"
no-section-label = true
git-repository-url = "https://github.com/stardussttx/mao-sama-retry"
git-repository-icon = "fa-github"
